# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/igor/Área de Trabalho/mpFelioe/mpfinal"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/igor/Área de Trabalho/mpFelioe/mpfinal"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/igor/Área de Trabalho/mpFelioe/mpfinal/CMakeFiles" "/home/igor/Área de Trabalho/mpFelioe/mpfinal/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/igor/Área de Trabalho/mpFelioe/mpfinal/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named projetoFinal

# Build rule for target.
projetoFinal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 projetoFinal
.PHONY : projetoFinal

# fast build rule for target.
projetoFinal/fast:
	$(MAKE) -f CMakeFiles/projetoFinal.dir/build.make CMakeFiles/projetoFinal.dir/build
.PHONY : projetoFinal/fast

# Manual pre-install relink rule for target.
projetoFinal/preinstall:
	$(MAKE) -f CMakeFiles/projetoFinal.dir/build.make CMakeFiles/projetoFinal.dir/preinstall
.PHONY : projetoFinal/preinstall

#=============================================================================
# Target rules for targets named projetoFinal_coverage

# Build rule for target.
projetoFinal_coverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 projetoFinal_coverage
.PHONY : projetoFinal_coverage

# fast build rule for target.
projetoFinal_coverage/fast:
	$(MAKE) -f CMakeFiles/projetoFinal_coverage.dir/build.make CMakeFiles/projetoFinal_coverage.dir/build
.PHONY : projetoFinal_coverage/fast

#=============================================================================
# Target rules for targets named elemento

# Build rule for target.
elemento: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 elemento
.PHONY : elemento

# fast build rule for target.
elemento/fast:
	$(MAKE) -f elemento/CMakeFiles/elemento.dir/build.make elemento/CMakeFiles/elemento.dir/build
.PHONY : elemento/fast

#=============================================================================
# Target rules for targets named cidade

# Build rule for target.
cidade: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cidade
.PHONY : cidade

# fast build rule for target.
cidade/fast:
	$(MAKE) -f cidade/CMakeFiles/cidade.dir/build.make cidade/CMakeFiles/cidade.dir/build
.PHONY : cidade/fast

#=============================================================================
# Target rules for targets named adaptador

# Build rule for target.
adaptador: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 adaptador
.PHONY : adaptador

# fast build rule for target.
adaptador/fast:
	$(MAKE) -f adaptador/CMakeFiles/adaptador.dir/build.make adaptador/CMakeFiles/adaptador.dir/build
.PHONY : adaptador/fast

#=============================================================================
# Target rules for targets named gerador

# Build rule for target.
gerador: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gerador
.PHONY : gerador

# fast build rule for target.
gerador/fast:
	$(MAKE) -f gerador/CMakeFiles/gerador.dir/build.make gerador/CMakeFiles/gerador.dir/build
.PHONY : gerador/fast

#=============================================================================
# Target rules for targets named interconexao

# Build rule for target.
interconexao: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 interconexao
.PHONY : interconexao

# fast build rule for target.
interconexao/fast:
	$(MAKE) -f interconexao/CMakeFiles/interconexao.dir/build.make interconexao/CMakeFiles/interconexao.dir/build
.PHONY : interconexao/fast

#=============================================================================
# Target rules for targets named repositorio

# Build rule for target.
repositorio: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 repositorio
.PHONY : repositorio

# fast build rule for target.
repositorio/fast:
	$(MAKE) -f repositorio/CMakeFiles/repositorio.dir/build.make repositorio/CMakeFiles/repositorio.dir/build
.PHONY : repositorio/fast

#=============================================================================
# Target rules for targets named relatorio

# Build rule for target.
relatorio: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 relatorio
.PHONY : relatorio

# fast build rule for target.
relatorio/fast:
	$(MAKE) -f relatorio/CMakeFiles/relatorio.dir/build.make relatorio/CMakeFiles/relatorio.dir/build
.PHONY : relatorio/fast

projetoFinal.o: projetoFinal.cpp.o
.PHONY : projetoFinal.o

# target to build an object file
projetoFinal.cpp.o:
	$(MAKE) -f CMakeFiles/projetoFinal.dir/build.make CMakeFiles/projetoFinal.dir/projetoFinal.cpp.o
.PHONY : projetoFinal.cpp.o

projetoFinal.i: projetoFinal.cpp.i
.PHONY : projetoFinal.i

# target to preprocess a source file
projetoFinal.cpp.i:
	$(MAKE) -f CMakeFiles/projetoFinal.dir/build.make CMakeFiles/projetoFinal.dir/projetoFinal.cpp.i
.PHONY : projetoFinal.cpp.i

projetoFinal.s: projetoFinal.cpp.s
.PHONY : projetoFinal.s

# target to generate assembly for a file
projetoFinal.cpp.s:
	$(MAKE) -f CMakeFiles/projetoFinal.dir/build.make CMakeFiles/projetoFinal.dir/projetoFinal.cpp.s
.PHONY : projetoFinal.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... projetoFinal"
	@echo "... projetoFinal_coverage"
	@echo "... rebuild_cache"
	@echo "... elemento"
	@echo "... cidade"
	@echo "... adaptador"
	@echo "... gerador"
	@echo "... interconexao"
	@echo "... repositorio"
	@echo "... relatorio"
	@echo "... projetoFinal.o"
	@echo "... projetoFinal.i"
	@echo "... projetoFinal.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

